### ISSUE TITLE
RFC: Don't wrap developer centric messages in translation function

### ISSUE THREAD

**Issue by ADmad** [CakeDC/auth#1]
Wrapping exception message (for e.g. those used in `Owner` class) in translation function doesn't serve any purpose IMHO. Nobody actually translates them. All they do is clutter the .po files when extracting message strings from plugins and create unnecessary headache for translators. We have also stopped using translation function for developer centric exception message in the core for same reason.

If you guys agree I can open an PR.

**Comment by steinkel** [comment]
I agree, let's keep only user facing messages translated
