### ISSUE TITLE
How do I add permissions from another plugin?

### ISSUE THREAD

**Issue by jeffreyroberts** [CakeDC/auth#11]
I tried to create a permissions.php file in the plugins/SharpAgent/config directory, however it wasn't loaded...

How can I add in my plugin bootstrap the following?

    return [
        'Users.SimpleRbac.permissions' => [
            [
                'role' => ['user', 'member', 'admin'],
                'plugin' => 'SharpAgent',
                'controller' => 'Agent',
                'action' => '*',
                'allowed' => true,
            ]
    ]];

**Comment by jeffreyroberts** [comment]
I tried plugins/Plugin/config/permissions.php but it didn't work, any ideas? should that work?

**Comment by steinkel** [comment]
You could do a Configure::read, apply your rules, then Configure::write inside your plugin's bootstrap file...
Let me know if that works :)

**Comment by jeffreyroberts** [comment]
Do I read it like so? 

     $rbac = Cake\Core\Configure::read('Users.SimpleRbac.permissions');

I am doing a 

    print_r($rbac);die('rbac');

right after the read, but it is outputting blank...

**Comment by jeffreyroberts** [comment]
Ok, I figured out that if I put the following in the plugin bootstrap, it gets overwritten, however, if I put it in an action, it doesn't get overwritten, but also doesn't do me any good at that point, since I cant put it in the bootstrap, where should I put it at?

        $rbac = Configure::read('Users.SimpleRbac.permissions');
        $rbac[] = [
            'role' => ['user', 'member', 'admin'],
            'plugin' => 'SharpAgent',
            'controller' => '*',
            'action' => '*',
            'allowed' => true,
        ];
        Configure::write('Users.SimpleRbac.permissions', $rbac);

**Comment by steinkel** [comment]
Hi @jeffreyroberts I've answered in SO, let me paste it here too for reference

You can load permissions.php file from the Plugin as it is doing now, but change the contents of permissions.php to preserve existing permissions defined in configuration, for example:

config/permissions.php

$permissions = [
    // add your app permissions here
    [
        // ...
    ],
];

// there are more permissions in this config key, defined across your plugins
$morePermissions = \Cake\Core\Configure::read('MyPermissions');
$allPerms = array_merge($permissions, $morePermissions);

return ['CakeDC/Auth.permissions' => $allPerms];

Then inside each plugin you could have:

YOUR_PLUGIN/config/bootstrap.php

$permissions = \Cake\Core\Configure::read('MyPermissions');
$someMorePermissions = [
    [
        // permissions injected into the app from this plugin
    ]
];

$permissions = array_merge((array)$permissions, $someMorePermissions);
\Cake\Core\Configure::write('MyPermissions', $permissions);

Allowing each plugin to dynamically inject/manage permissions into the app.

I've created a c9.io environment with this code here https://ide.c9.io/steinkel/users-35-custom-permissions

**Comment by tgoeminne** [comment]
you would wonder why this is not done out of the box... its like the most generic thing you put you permissions file in the plugin folder config. You d expect it to work like that... Cakephp people complained about it 7 years ago, but do you think anybody changes it? No...

**Comment by steinkel** [comment]
@tgoeminne `autoload_config` defaults to `permissions`, so it will load the permissions.php file by default, when it's present under your `config` folder. Is this the behavior you are looking for?

Thanks,
