### ISSUE TITLE
Permissions with empty value are ignored

### ISSUE THREAD

**Issue by CauanCabral** [CakeDC/auth#19]
Hi,

In the source code there a parameter to allow an empty field from request pass as valid, but that parameter are never read.

I tried write a permission rule as below, to allow anyone access any action without a prefix:

```php
[
        'role' => '*',
        'prefix' => null,
        'extension' => '*',
        'plugin' => '*',
        'controller' => '*',
        'action' => '*',
]
```

But the method `_matchOrAsterisk` fail because `in_array(null, []) === false`.

**Comment by rochamarcelo** [comment]
Hi,

Have you tried the followng 'prefix' => [null]

**Comment by CauanCabral** [comment]
Hey, thanks @rochamarcelo . 
Seems to work with `[null]`, but I don't think that make sense =[

**Comment by rochamarcelo** [comment]
Yeah, I don't think it makes sense, there is an issue while casting to array
