### ISSUE TITLE
PHP Notice with last CakePHP version

### ISSUE THREAD

**Issue by viniciusbig** [CakeDC/auth#28]
CakeDC/Users is breaking with the recently released CakePHP 3.6.12.

Notice (1024): Undefined property: PagesController::$Cookie in /cakesandbox/vendor/cakedc/auth/src/Auth/RememberMeAuthenticate.php on line 42 [CORE/src/Controller/Controller.php, line 387]

I'm using CakeDC/Users and this repo is a dependency.

**Comment by viniciusbig** [comment]
I could reproduce the error in a fresh install of cake.

 - install a fresh cake. (3.6.12)
 - install cakedc/users
 - load plugin and migrations
 - try to open my_app.dev/users/users

**Comment by steinkel** [comment]
thank you for reporting it, we noticed it too and a fix is on its way...

**Comment by thumbtech** [comment]
FYI inclusion of 
`$this->loadComponent('Cookie'); // to support old CakeDC/Auth`
in controller initialize will handle this.

However, this cookie component has been deprecated since 3.5.0, so fix should go to new cookies and dependency noted.

**Comment by steinkel** [comment]
We actually require 3.6
https://github.com/CakeDC/auth/blob/master/composer.json#L29

so the fix should not break existing code... are you experiencing issues after the fix?

Thanks,

**Comment by thumbtech** [comment]
Yes thanks 3.0.1 fixed!

Although if requiring 3.6, why not go the
`...
$cookie = $request->getCookie($cookieName);
...`
route?

**Comment by steinkel** [comment]
yes, that could be an improvement, keep in mind we have a refactor in progress to use the new cakephp/authentication plugin and some other improvements, so it'll make sense to wait until we manage to merge it.

Thanks,

**Comment by gerrymcdonnell** [comment]
> FYI inclusion of
> `$this->loadComponent('Cookie'); // to support old CakeDC/Auth`
> in controller initialize will handle this.
> 
> However, this cookie component has been deprecated since 3.5.0, so fix should go to new cookies and dependency noted.

Thanks for that, fixed an issue i had with cake 3.6 and cakedc/users": "^6.0.1
