### ISSUE TITLE
Assigning multiple Roles to one user

### ISSUE THREAD

**Issue by kaihoefler** [CakeDC/auth#30]
The current authentication is expecting a field which stores the role of the user. 
In the permission.php permission can be checked against this role of the user.

I have an application where the user should be assigend to more than one role.
E.g. a user can be athlete, trainer and club_admin at the same time.

I was wondering if it would be possible to extend the configuration in a way that an association can be used instead of an attribute of the user table: (e.g. `user_roles._ids` as it is used in views)

The solution I have in view is:
The developer extends the user model with an association to the roles the user is mapped to.
In configuration of the auth plugin the developer can configure that the relation is used to check  permission.
` 'role_field' => 'user_roles._ids',`

**Comment by steinkel** [comment]
Yes, it's possible and we did it in the past for a number of projects. Another solution would be creating a NEW role, with the aggregation of all these permissions, like `athlete_trainer_clubAdmin` and mixing the permissions. Depending on your application this option would make sense or not...
