### ISSUE TITLE
How can a user enter a site by a token? api key authorization? cakedc 

### ISSUE THREAD

**Issue by emiliano-idata** [CakeDC/auth#35]
hello, I have an application working with the plugin cakedc users, I have two diferent roles, I need the same users can enter the site through a security token, is this possible with the api key and token?

ApiKeyAuthenticate? some example, thanks a lot.

**Comment by steinkel** [comment]
Emiliano, you can use the ApiKeyAuthenticate to configure a token column in your database, then generate a random token for each user (check the column in the db has a value).

The ApiKeyAuthenticate allows you to configure how you are going to pass the token, for example through a query string, or a header.

Defaults are:
https://github.com/CakeDC/auth/blob/3.next/src/Auth/ApiKeyAuthenticate.php#L31

So, using default config, you'll need to add a token for the user in column `api_token` and create a request to your API using an url like: `https://example.com/controller/action?api_key=XXX`

Thanks,
