### ISSUE TITLE
RFC - Convert SimpleRbacAuthorize into a standalone class.

### ISSUE THREAD

**Issue by ADmad** [CakeDC/auth#5]
Currently `SimpleRbacAuthorize` can only be used as an authorize adapter for the `AuthComponent`. It would be nice if it was converted into a standalone lib which could then be used through a middleware.

**Comment by steinkel** [comment]
I agree on this, so we can use it from other plugins and our new psr7 compatible layers, I'll work on this ASAP.

**Comment by steinkel** [comment]
closed per #9
