### ISSUE TITLE
Error after update from 6.1.0 to 6.2.0

### ISSUE THREAD

**Issue by rudy1976s** [CakeDC/auth#65]
I have just updated from 6.1.0 to 6.2.0 and I received this errors after login

Warning (2): class_implements(): object or string expected [ROOT/vendor/cakedc/auth/src/Authentication/Webauthn2fAuthenticationCheckerFactory.php, line 32]

I had to revert back to 6.1 to make my app work again

Thank you

Rudy

**Comment by rochamarcelo** [comment]
How did you update to 6.2.0 and are you using cakedc/users @rudy1976s ?

See the new keys added (https://github.com/CakeDC/users/releases/tag/9.3.0)
```
'Webauthn2fa' => [
        'enabled' => false,
        'appName' => null,//App must set a valid name here
        'id' => null,//default value is the current domain
        'checker' => \CakeDC\Auth\Authentication\DefaultWebauthn2fAuthenticationChecker::class,
        'startAction' => [
            'plugin' => 'CakeDC/Users',
            'controller' => 'Users',
            'action' => 'webauthn2fa',
            'prefix' => false,
        ]
    ]
```
